# Generated by Django 5.0.7 on 2024-07-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiji', '0006_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=450),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=450),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=450),
        ),
    ]
