# Generated by Django 5.0.7 on 2024-07-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiji', '0008_product_product_url'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
    ]
